// <auto-generated />
namespace ConsoleApp28.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Agefrominttofloat : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Agefrominttofloat));
        
        string IMigrationMetadata.Id
        {
            get { return "201711300850264_Age  from int to float"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
